name: Time_Do
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  animations: ^2.0.7
  cupertino_icons: ^1.0.2
  date_picker_timeline: null
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: ^12.0.3
  flutter_native_timezone: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_staggered_grid_view: null
  get: ^4.6.5
  get_storage: ^2.0.3
  getwidget: ^3.0.1
  google_fonts: ^3.0.1
  intl: null
  lottie: ^1.4.3
  share: null
  sqflite: ^2.1.0
  string_stats: ^0.1.0
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/2.PNG"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/2.PNG"
    background_color: "#hexcode"
    theme_color: "#hexcode"

  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Molhim
      fonts:
        - asset: assets/fonts/Molhim Bold.otf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
